# Change these first
owner: MrCodeEU # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Main (Unraid)
    url: https://mljr.dev
  - name: Secondary (CasaOS nuc)
    url: https://casa.mljr.dev
  - name: Home Assistant
    url: https://assistant.mljr.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  name: mljr.dev services uptime
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  baseUrl: /uptime
  introTitle: "Michael Ludwig Reinegger Services status page"
  introMessage: Here is a list of all services hosted by me and if they are running or if there is any maintainance. There is also an response time meassurement.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
